### ISSUE TITLE
Remove unused code system_tasks.c

### ISSUE THREAD

**Issue by LouisTGT** [LouisTGT/Enigma#14]
void SYS_Tasks ( void )
{
    /\* Maintain the state machines of all library modules executing polled in
    the system. */

```
/* Maintain system services */
SYS_DEVCON_Tasks(sysObj.sysDevcon);

/* Maintain Device Drivers */
DRV_TMR_Tasks(sysObj.drvTmr0);
/* USB Device layer tasks routine */ 
USB_DEVICE_Tasks(sysObj.usbDevObject0);
```

Removed    /\* Maintain the application's state machine. */
Removed    //APP_Tasks();
}

**Comment by fonTGT** [comment]
^__^

**Comment by LouisTGT** [comment]
Reviewed
