### ISSUE TITLE
Remove unnecessary variable in file xcp.c

### ISSUE THREAD

**Issue by LouisTGT** [LouisTGT/Enigma#20]
uint8_t **attribute**((space(data),address(0xA000FF00))) AddrStore[XCP_BUFFER_SIZE] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                                                                        0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                                                                        0,0,0,0,0};

**Comment by fonTGT** [comment]
^________^

**Comment by LouisTGT** [comment]
Reviewed
