### ISSUE TITLE
Wait for FPGA_DONE before start task scheduler.

### ISSUE THREAD

**Issue by LouisTGT** [LouisTGT/Enigma#23]
Must wait for FPGA ready in system_init before starting task scheduler.

/\* Place the App state machine in its initial state. _/
/_ Wait FPGA_DONE*/
# define PinGet_FpgaDone     PLIB_PORTS_PinGet(PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_3)

```
while(!PinGet_FpgaDone) {

}
```

**Comment by fonTGT** [comment]
ka

**Comment by LouisTGT** [comment]
Reviewed
