### ISSUE TITLE
Source file template

### ISSUE THREAD

**Issue by MichaelScofield2** [LouisTGT/Enigma#30]
/*******************************************************************************
  miniHILBaseSoftware EEPROM Source File

  Company:
    ThaiGerTec Co., Ltd.

  project:
    miniHILBaseSoftware

  File Name:
    EEPROM.c

  Summary:
    This file contains the source code for the EEPROM on baseboard.

  Description:

  Version:

  Release date:  

 *******************************************************************************/

**Comment by LouisTGT** [comment]
Sample template

/*****************************************************************************_/
/_                                                                            _/
/_Company: ThaiGerTec Co., Ltd.                                               _/
/_                                                                            _/
/_Project: miniHILBaseSoftware                                                _/
/_                                                                            _/
/_File Name: xxx.c                                                            _/
/_                                                                            _/
/_Summary:                                                                    _/
/_                                                                            _/
/_                                                                            _/
/_Version:                                                                    _/
/_                                                                            _/
/_Date created:                                                               _/
/_                                                                            _/
/_Created by:                                                                 _/
/_                                                                            */
/*****************************************************************************_/
/_                                                                            _/
/_ MODIFICATION HISTORY:                                                      _/
/_                                                                            _/
/_ Date:       Name:          Change Description:                             _/
/_                                                                            _/
/_ 18.01.2013  xxxxx          xxxxxxxx                                        _/
/_                                                                            _/
/_ 28.06.2011  xxxxxx         xxxxxxxxx                                       _/
/_                                                                            */
/******************************************************************************/

/**
- Write function description here
- @param var_name  its description
- @return return description  
  */
  xxx func(xxx var1, xxx var2)
  {

}

**Comment by LouisTGT** [comment]
See in svn://192.168.1.4:4501/FirmwareGroup/10_ Standard/template_code.c
