### ISSUE TITLE
PMP read cannot put in Taskmanager_1ms()

### ISSUE THREAD

**Issue by Jedyubz** [LouisTGT/Enigma#38]
It take time more than Taskmanager_1ms() when DRV_PMP0_Read was called  to read 512 address of FPGA memory data in Taskmanager_1m(). It spent around 2 mS to read 512 address. But DRV_PMP0_Write spent only 116 uS.

**Comment by MichaelScofield2** [comment]
miniHIL BaseSoftware Version 2.0 is coming soon. More over, this topic will fixed

Copy that.
